apiVersion: apps/v1
kind: Deployment
metadata:
  name: dop-rs
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: my-dep
  template:
    metadata: 
      labels:
        app: my-dep 
    spec:
      containers:
      - name: my-pod
        image: nginx:1.8
        ports:
        - containerPort: 80
  
      
    
