apiVersion: v1
kind: Pod
metadata:
  name: envsecret
spec:
  containers:
  - name: env
    image: nginx
    env:
    - name:  ENV_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name:  ENV_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
  restartPolicy: Never

