apiVersion: v1
kind: Pod
metadata:
  name: mysecret-pod
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: food-vol
      mountPath: "/etc/food"
      readOnly: true
  volumes:
  - name: food-vol
    secret:
      secretName: mysecret 
